config/routes.rb
Interview::Application.routes.draw do

  resources :items

  resource :importer, :controller => "importer", :only => [:new, :create]

  root :to => "pages#readme"

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates_presence_of :name, :price, :provider, :gender, :category, :description

  def self.create_multiples_from_csv(upload_file)
    begin 
      #saving csv file on tmp directory
      file_path = "#{Rails.root}/tmp/#{upload_file.original_filename}"
      File.open(file_path, "wb") {|f| f.write(upload_file.read)}
      return self.read_csv_and_populate_items(file_path)
    rescue
      return false
    end
  end

  def self.read_csv_and_populate_items(file_path)
    begin
      Item.transaction do
        # read CSV file and create items if it don't exist
        CSV.read(file_path).each_with_index do |item, i|
          next if i == 0

          attributes = {
            :name        => self.sanitize_text(item[0]),
            #:image_file => item[1] # we could you paperclip here
            :provider    => self.sanitize_text(item[2]),
            :price       => self.sanitize_decimal(item[3]),
            :gender      => self.sanitize_text(item[4]),
            :category    => self.sanitize_text(item[5]),
            :description => self.sanitize_text(item[6]),
            #:sku        => item[] #we don't have sku on csv file
          }
          
          # if the item already exist update its price and description, if not create a new item
          if Item.where(attributes.select{|k| ![:price, :description].include?(k)}).count > 0
            db_item = Item.where(attributes.select{|k| ![:price, :description].include?(k)}).first
            db_item.update_attributes(attributes.select{|k| [:price, :description].include?(k)})
          else
            Item.create!(attributes)
          end
        end
        return true
      end
      return false
    rescue
      return false
    end
  end

  protected
    # sanitize decimal numbers, clean any typo before try add it to database
    def self.sanitize_decimal(number)
      unless number.is_a?(Float) or number.is_a?(Integer)
        number = number.match(/(\d+\.\d+|\d+)/)[0]
      end
      number.to_f
    end
    
    def self.sanitize_text(text)
      # Iconv.conv("UTF-8//IGNORE", "US-ASCII", item[0]) fix problem with postgresql encode
      Iconv.conv("UTF-8//IGNORE", "US-ASCII", text)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/importer_controller.rb
class ImporterController < ApplicationController
  def new
  end

  def create
    if Item.create_multiples_from_csv(params[:importer][:products_list])
      flash[:notice] = "Items successfuly imported"
    else
      flash[:notice] = "There is some problem on the import, please try again"
    end
    redirect_to new_importer_path
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def readme
    open("#{Rails.root}/README.markdown") do |f|
      render :text => BlueCloth::new(f.read).to_html
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/importer_helper.rb
module ImporterHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/importer/new.html.erb
<h1>Import your Products Here</h1>
<%= content_tag(:div, flash[:notice]) if flash[:notice] %>

<%= form_tag importer_path, :multipart => true do %>
  <p>
    <%= label_tag "add your products list" %>
    <br />
    <%= file_field_tag "importer[products_list]" %>
  </p>
  <p>
    <%= submit_tag "upload" %>
<% end %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :sku %><br />
    <%= f.text_field :sku %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Price</th>
    <th>Sku</th>
    <th>Description</th>
    <th>Provider</th>
    <th>Gender</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= item.name %></td>
    <td><%= item.price %></td>
    <td><%= item.sku %></td>
    <td><%= truncate item.description, :lenght => 50 %></td>
    <td><%= item.provider %></td>
    <td><%= item.gender %></td>
    <td><%= item.category %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>

<p>
  <b>Sku:</b>
  <%= @item.sku %>
</p>

<p>
  <b>Description:</b>
  <%= @item.description %>
</p>

<p>
  <b>Provider:</b>
  <%= @item.provider %>
</p>

<p>
  <b>Gender:</b>
  <%= @item.gender %>
</p>

<p>
  <b>Category:</b>
  <%= @item.category %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interview</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>